#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_Skin_AK74M_02

#include "Basic.hpp"

#include "POLYGON_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Item_Skin_AK74M_02.BP_Item_Skin_AK74M_02_C
// 0x0008 (0x0360 - 0x0358)
class ABP_Item_Skin_AK74M_02_C final : public AItem_Module_Skin
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Item_Skin_AK74M_02_C">();
	}
	static class ABP_Item_Skin_AK74M_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Item_Skin_AK74M_02_C>();
	}
};
static_assert(alignof(ABP_Item_Skin_AK74M_02_C) == 0x000008, "Wrong alignment on ABP_Item_Skin_AK74M_02_C");
static_assert(sizeof(ABP_Item_Skin_AK74M_02_C) == 0x000360, "Wrong size on ABP_Item_Skin_AK74M_02_C");
static_assert(offsetof(ABP_Item_Skin_AK74M_02_C, DefaultSceneRoot) == 0x000358, "Member 'ABP_Item_Skin_AK74M_02_C::DefaultSceneRoot' has a wrong offset!");

}

