#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PG_Menu_Character

#include "Basic.hpp"

#include "BP_PG_Menu_Character_classes.hpp"
#include "BP_PG_Menu_Character_parameters.hpp"


namespace SDK
{

// Function BP_PG_Menu_Character.BP_PG_Menu_Character_C.ExecuteUbergraph_BP_PG_Menu_Character
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PG_Menu_Character_C::ExecuteUbergraph_BP_PG_Menu_Character(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PG_Menu_Character_C", "ExecuteUbergraph_BP_PG_Menu_Character");

	Params::BP_PG_Menu_Character_C_ExecuteUbergraph_BP_PG_Menu_Character Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PG_Menu_Character.BP_PG_Menu_Character_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PG_Menu_Character_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PG_Menu_Character_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

