#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_Jump_End

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_Jump_End.CameraShake_Jump_End_C
// 0x0000 (0x0210 - 0x0210)
class UCameraShake_Jump_End_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_Jump_End_C">();
	}
	static class UCameraShake_Jump_End_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_Jump_End_C>();
	}
};
static_assert(alignof(UCameraShake_Jump_End_C) == 0x000010, "Wrong alignment on UCameraShake_Jump_End_C");
static_assert(sizeof(UCameraShake_Jump_End_C) == 0x000210, "Wrong size on UCameraShake_Jump_End_C");

}

