#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_RifleShot

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_RifleShot.CameraShake_RifleShot_C
// 0x0000 (0x0210 - 0x0210)
class UCameraShake_RifleShot_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraShake_RifleShot_C">();
	}
	static class UCameraShake_RifleShot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_RifleShot_C>();
	}
};
static_assert(alignof(UCameraShake_RifleShot_C) == 0x000010, "Wrong alignment on UCameraShake_RifleShot_C");
static_assert(sizeof(UCameraShake_RifleShot_C) == 0x000210, "Wrong size on UCameraShake_RifleShot_C");

}

