#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Task_Character_SetupByTeam

#include "Basic.hpp"

#include "Task_Character_SetupByTeam_classes.hpp"
#include "Task_Character_SetupByTeam_parameters.hpp"


namespace SDK
{

// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.ExecuteUbergraph_Task_Character_SetupByTeam
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTask_Character_SetupByTeam_C::ExecuteUbergraph_Task_Character_SetupByTeam(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "ExecuteUbergraph_Task_Character_SetupByTeam");

	Params::Task_Character_SetupByTeam_C_ExecuteUbergraph_Task_Character_SetupByTeam Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.OnIsMemberMySquad_Event
// (BlueprintCallable, BlueprintEvent)

void UTask_Character_SetupByTeam_C::OnIsMemberMySquad_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "OnIsMemberMySquad_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.OnSetPlayerState_Event
// (BlueprintCallable, BlueprintEvent)

void UTask_Character_SetupByTeam_C::OnSetPlayerState_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "OnSetPlayerState_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.OnSetPlayerStateLocal_Event
// (BlueprintCallable, BlueprintEvent)

void UTask_Character_SetupByTeam_C::OnSetPlayerStateLocal_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "OnSetPlayerStateLocal_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.OnSetTeam_Event
// (BlueprintCallable, BlueprintEvent)

void UTask_Character_SetupByTeam_C::OnSetTeam_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "OnSetTeam_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.ReceiveActivate
// (Event, Protected, BlueprintEvent)

void UTask_Character_SetupByTeam_C::ReceiveActivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "ReceiveActivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.ScaleCharacterByDistance
// (BlueprintCallable, BlueprintEvent)

void UTask_Character_SetupByTeam_C::ScaleCharacterByDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "ScaleCharacterByDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Task_Character_SetupByTeam.Task_Character_SetupByTeam_C.SetMaterialsByTeam
// (Public, BlueprintCallable, BlueprintEvent)

void UTask_Character_SetupByTeam_C::SetMaterialsByTeam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_Character_SetupByTeam_C", "SetMaterialsByTeam");

	UObject::ProcessEvent(Func, nullptr);
}

}

