#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CreateServer

#include "Basic.hpp"

#include "UI_CreateServer_classes.hpp"
#include "UI_CreateServer_parameters.hpp"


namespace SDK
{

// Function UI_CreateServer.UI_CreateServer_C.BndEvt__Button_Play_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CreateServer_C::BndEvt__Button_Play_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "BndEvt__Button_Play_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CreateServer.UI_CreateServer_C.BndEvt__Button_StartServer_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CreateServer_C::BndEvt__Button_StartServer_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "BndEvt__Button_StartServer_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CreateServer.UI_CreateServer_C.BndEvt__UI_CreateServer_Button_CreateServer_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CreateServer_C::BndEvt__UI_CreateServer_Button_CreateServer_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "BndEvt__UI_CreateServer_Button_CreateServer_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CreateServer.UI_CreateServer_C.BndEvt__UI_CreateServer_Button_ShowPassword_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_CreateServer_C::BndEvt__UI_CreateServer_Button_ShowPassword_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "BndEvt__UI_CreateServer_Button_ShowPassword_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CreateServer.UI_CreateServer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_CreateServer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CreateServer.UI_CreateServer_C.CreateServer
// (BlueprintCallable, BlueprintEvent)

void UUI_CreateServer_C::CreateServer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "CreateServer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CreateServer.UI_CreateServer_C.ExecuteUbergraph_UI_CreateServer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CreateServer_C::ExecuteUbergraph_UI_CreateServer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "ExecuteUbergraph_UI_CreateServer");

	Params::UI_CreateServer_C_ExecuteUbergraph_UI_CreateServer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CreateServer.UI_CreateServer_C.OnRequestServerFinished_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSuccessful                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CreateServer_C::OnRequestServerFinished_Event(bool IsSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "OnRequestServerFinished_Event");

	Params::UI_CreateServer_C_OnRequestServerFinished_Event Parms{};

	Parms.IsSuccessful = IsSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CreateServer.UI_CreateServer_C.OnUpdatePlayerCombinedInfo_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<EModifiedData>                   ModifiedData                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FString                           CustomString                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUI_CreateServer_C::OnUpdatePlayerCombinedInfo_Event(const TArray<EModifiedData>& ModifiedData, const class FString& CustomString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "OnUpdatePlayerCombinedInfo_Event");

	Params::UI_CreateServer_C_OnUpdatePlayerCombinedInfo_Event Parms{};

	Parms.ModifiedData = std::move(ModifiedData);
	Parms.CustomString = std::move(CustomString);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CreateServer.UI_CreateServer_C.ParsePlayerCombinedInfo
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_CreateServer_C::ParsePlayerCombinedInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "ParsePlayerCombinedInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_CreateServer.UI_CreateServer_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_CreateServer_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "PreConstruct");

	Params::UI_CreateServer_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_CreateServer.UI_CreateServer_C.SetSelectedMap
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_CreateServer_Map_C*           NewMap                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_CreateServer_C::SetSelectedMap(class UUI_CreateServer_Map_C* NewMap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_CreateServer_C", "SetSelectedMap");

	Params::UI_CreateServer_C_SetSelectedMap Parms{};

	Parms.NewMap = NewMap;

	UObject::ProcessEvent(Func, &Parms);
}

}

