#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Crosshair

#include "Basic.hpp"

#include "UI_Crosshair_classes.hpp"
#include "UI_Crosshair_parameters.hpp"


namespace SDK
{

// Function UI_Crosshair.UI_Crosshair_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Crosshair_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Crosshair.UI_Crosshair_C.ExecuteUbergraph_UI_Crosshair
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::ExecuteUbergraph_UI_Crosshair(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "ExecuteUbergraph_UI_Crosshair");

	Params::UI_Crosshair_C_ExecuteUbergraph_UI_Crosshair Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair.UI_Crosshair_C.OnApplyGunDamage_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bHeadshot                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::OnApplyGunDamage_Event(bool bHeadshot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "OnApplyGunDamage_Event");

	Params::UI_Crosshair_C_OnApplyGunDamage_Event Parms{};

	Parms.bHeadshot = bHeadshot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair.UI_Crosshair_C.OnPossessedPawnChanged_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            OldPawn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class APawn*                            NewPawn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::OnPossessedPawnChanged_Event_0(class APawn* OldPawn, class APawn* NewPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "OnPossessedPawnChanged_Event_0");

	Params::UI_Crosshair_C_OnPossessedPawnChanged_Event_0 Parms{};

	Parms.OldPawn = OldPawn;
	Parms.NewPawn = NewPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair.UI_Crosshair_C.OnSetCurrentGun_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AItem_Gun_General*                OldCurrentGun                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::OnSetCurrentGun_Event(class AItem_Gun_General* OldCurrentGun)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "OnSetCurrentGun_Event");

	Params::UI_Crosshair_C_OnSetCurrentGun_Event Parms{};

	Parms.OldCurrentGun = OldCurrentGun;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair.UI_Crosshair_C.OnSetPlayerState_Event
// (BlueprintCallable, BlueprintEvent)

void UUI_Crosshair_C::OnSetPlayerState_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "OnSetPlayerState_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Crosshair.UI_Crosshair_C.SetCrosshairPosition
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector2D                        InPosition                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::SetCrosshairPosition(const struct FVector2D& InPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "SetCrosshairPosition");

	Params::UI_Crosshair_C_SetCrosshairPosition Parms{};

	Parms.InPosition = std::move(InPosition);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Crosshair.UI_Crosshair_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Crosshair_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Crosshair_C", "Tick");

	Params::UI_Crosshair_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

