#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ExitGame

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_ExitGame.UI_ExitGame_C.ExecuteUbergraph_UI_ExitGame
// 0x0010 (0x0010 - 0x0000)
struct UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3843[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame) == 0x000008, "Wrong alignment on UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame");
static_assert(sizeof(UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame) == 0x000010, "Wrong size on UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame");
static_assert(offsetof(UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame, EntryPoint) == 0x000000, "Member 'UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'UI_ExitGame_C_ExecuteUbergraph_UI_ExitGame::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");

}

