#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Game_Minimap_Map

#include "Basic.hpp"

#include "UI_Game_Minimap_Map_classes.hpp"
#include "UI_Game_Minimap_Map_parameters.hpp"


namespace SDK
{

// Function UI_Game_Minimap_Map.UI_Game_Minimap_Map_C.AddOtherIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Owner                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Game_Minimap_Map_C::AddOtherIcon(class AActor* Owner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_Minimap_Map_C", "AddOtherIcon");

	Params::UI_Game_Minimap_Map_C_AddOtherIcon Parms{};

	Parms.Owner = Owner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Game_Minimap_Map.UI_Game_Minimap_Map_C.AddOtherPlayerIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            PlayerCharacter                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Game_Minimap_Map_C::AddOtherPlayerIcon(class APawn* PlayerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_Minimap_Map_C", "AddOtherPlayerIcon");

	Params::UI_Game_Minimap_Map_C_AddOtherPlayerIcon Parms{};

	Parms.PlayerCharacter = PlayerCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Game_Minimap_Map.UI_Game_Minimap_Map_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Game_Minimap_Map_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_Minimap_Map_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Game_Minimap_Map.UI_Game_Minimap_Map_C.ConvertCharacterPositionToMap
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  X                                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Y                                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Game_Minimap_Map_C::ConvertCharacterPositionToMap(double* X, double* Y)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_Minimap_Map_C", "ConvertCharacterPositionToMap");

	Params::UI_Game_Minimap_Map_C_ConvertCharacterPositionToMap Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (X != nullptr)
		*X = Parms.X;

	if (Y != nullptr)
		*Y = Parms.Y;
}


// Function UI_Game_Minimap_Map.UI_Game_Minimap_Map_C.ExecuteUbergraph_UI_Game_Minimap_Map
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Game_Minimap_Map_C::ExecuteUbergraph_UI_Game_Minimap_Map(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_Minimap_Map_C", "ExecuteUbergraph_UI_Game_Minimap_Map");

	Params::UI_Game_Minimap_Map_C_ExecuteUbergraph_UI_Game_Minimap_Map Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Game_Minimap_Map.UI_Game_Minimap_Map_C.OnLoaded_136039F0430841AA8E176F891F8DB5F6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Game_Minimap_Map_C::OnLoaded_136039F0430841AA8E176F891F8DB5F6(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_Minimap_Map_C", "OnLoaded_136039F0430841AA8E176F891F8DB5F6");

	Params::UI_Game_Minimap_Map_C_OnLoaded_136039F0430841AA8E176F891F8DB5F6 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Game_Minimap_Map.UI_Game_Minimap_Map_C.SetMapPosition
// (BlueprintCallable, BlueprintEvent)

void UUI_Game_Minimap_Map_C::SetMapPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Game_Minimap_Map_C", "SetMapPosition");

	UObject::ProcessEvent(Func, nullptr);
}

}

