#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "POLYGON_structs.hpp"


namespace SDK::Params
{

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List
// 0x00B8 (0x00B8 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C6D[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_PG_PlayerState_Game_C*              K2Node_DynamicCast_AsBP_PG_Player_State_Game;      // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C6E[0x3];                                     // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C6F[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x002E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C70[0x1];                                     // 0x002F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0030(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C71[0x3];                                     // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EModifiedData>                         K2Node_CustomEvent_ModifiedData;                   // 0x0070(0x0010)(ConstParm, ReferenceParm)
	class FString                                 K2Node_CustomEvent_CustomString;                   // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EModifiedData                                 CallFunc_Array_Get_Item;                           // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C72[0x3];                                     // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C73[0x1];                                     // 0x009B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(TArray<EModifiedData>& ModifiedData, const class FString& CustomString)> K2Node_CreateDelegate_OutputDelegate;              // 0x009C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C74[0x4];                                     // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_C* CallFunc_FindParentWidgetOfType_ReturnValue;       // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List) == 0x000008, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List) == 0x0000B8, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, EntryPoint) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_DynamicCast_AsBP_PG_Player_State_Game) == 0x000010, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_DynamicCast_AsBP_PG_Player_State_Game' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, Temp_bool_True_if_break_was_hit_Variable) == 0x000024, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, Temp_int_Array_Index_Variable) == 0x000028, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_Not_PreBool_ReturnValue) == 0x00002C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, Temp_bool_Has_Been_Initd_Variable) == 0x00002D, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_Event_IsDesignTime) == 0x00002E, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_Event_MyGeometry) == 0x000030, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_Event_InDeltaTime) == 0x000068, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, Temp_bool_IsClosed_Variable) == 0x00006C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_CustomEvent_ModifiedData) == 0x000070, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_CustomEvent_ModifiedData' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_CustomEvent_CustomString) == 0x000080, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_CustomEvent_CustomString' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_Array_Get_Item) == 0x000090, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_Array_Length_ReturnValue) == 0x000094, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000098, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_Less_IntInt_ReturnValue) == 0x000099, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_BooleanAND_ReturnValue) == 0x00009A, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, K2Node_CreateDelegate_OutputDelegate) == 0x00009C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List, CallFunc_FindParentWidgetOfType_ReturnValue) == 0x0000B0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ExecuteUbergraph_UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List::CallFunc_FindParentWidgetOfType_ReturnValue' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.GetModuleType
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_GetModuleType final
{
public:
	EGunModuleType                                Param_Module_Type;                                 // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_GetModuleType) == 0x000001, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_GetModuleType");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_GetModuleType) == 0x000001, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_GetModuleType");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_GetModuleType, Param_Module_Type) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_GetModuleType::Param_Module_Type' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.OnUpdatePlayerCombinedInfo_Event
// 0x0020 (0x0020 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event final
{
public:
	TArray<EModifiedData>                         ModifiedData;                                      // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FString                                 CustomString;                                      // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event) == 0x000008, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event) == 0x000020, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event, ModifiedData) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event::ModifiedData' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event, CustomString) == 0x000010, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_OnUpdatePlayerCombinedInfo_Event::CustomString' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.ParseModules
// 0x00F0 (0x00F0 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules final
{
public:
	TArray<class UClass*>                         L_Modules;                                         // 0x0000(0x0010)(Edit, BlueprintVisible)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsItem_Gun_General;        // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C75[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C76[0x4];                                     // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGunModulesInfo*                        K2Node_DynamicCast_AsGun_Modules_Info;             // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C77[0x6];                                     // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGunModuleInfo                         CallFunc_Array_Get_Item_1;                         // 0x0058(0x0040)(ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C78[0x2];                                     // 0x009E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClass*>                         CallFunc_SortModulesByRare_SortedModules;          // 0x00A0(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C79[0x4];                                     // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_Item_Entry_C* CallFunc_SpawnObject_ReturnValue;                  // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_Slot_C* CallFunc_GetSlotByModuleType_Slot;                 // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsItem_Gun_General_1;      // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C7A[0x3];                                     // 0x00D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C7B[0x3];                                     // 0x00D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_Item_Entry_C* CallFunc_SpawnObject_ReturnValue_1;                // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules) == 0x000008, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules) == 0x0000F0, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, L_Modules) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::L_Modules' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, Temp_int_Array_Index_Variable) == 0x000010, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, Temp_int_Array_Index_Variable_1) == 0x00001C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, K2Node_ClassDynamicCast_AsItem_Gun_General) == 0x000020, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::K2Node_ClassDynamicCast_AsItem_Gun_General' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, K2Node_ClassDynamicCast_bSuccess) == 0x000028, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Array_Get_Item) == 0x000030, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_LoadAsset_Blocking_ReturnValue) == 0x000040, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_LoadAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, K2Node_DynamicCast_AsGun_Modules_Info) == 0x000048, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::K2Node_DynamicCast_AsGun_Modules_Info' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000051, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Array_Get_Item_1) == 0x000058, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Array_Length_ReturnValue_1) == 0x000098, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Less_IntInt_ReturnValue) == 0x00009C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_IsValidClass_ReturnValue) == 0x00009D, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_SortModulesByRare_SortedModules) == 0x0000A0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_SortModulesByRare_SortedModules' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Array_Add_ReturnValue) == 0x0000B0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_SpawnObject_ReturnValue) == 0x0000B8, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_GetSlotByModuleType_Slot) == 0x0000C0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_GetSlotByModuleType_Slot' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, K2Node_ClassDynamicCast_AsItem_Gun_General_1) == 0x0000C8, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::K2Node_ClassDynamicCast_AsItem_Gun_General_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, K2Node_ClassDynamicCast_bSuccess_1) == 0x0000D0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, Temp_int_Loop_Counter_Variable_1) == 0x0000D4, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000D8, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000DC, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_SpawnObject_ReturnValue_1) == 0x0000E0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_SpawnObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0000E8, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ParseModules::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_PreConstruct");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_PreConstruct) == 0x000001, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_PreConstruct");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.SetModuleType
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SetModuleType final
{
public:
	EGunModuleType                                ModuleType;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SetModuleType) == 0x000001, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SetModuleType");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SetModuleType) == 0x000001, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SetModuleType");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SetModuleType, ModuleType) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SetModuleType::ModuleType' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.SortModulesByRare
// 0x0080 (0x0080 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare final
{
public:
	TArray<class UClass*>                         Modules;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class UClass*>                         SortedModules;                                     // 0x0010(0x0010)(Parm, OutParm)
	int32                                         L_ArrayIndex;                                      // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          L_Sorted;                                          // 0x0024(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C7C[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C7D[0x4];                                     // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_Array_Get_Item;                           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_Array_Get_Item_1;                         // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsItem_Module_Skin;        // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C7E[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_ClassDynamicCast_AsItem_Module_Skin_1;      // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C7F[0x3];                                     // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0075(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C80[0x2];                                     // 0x0076(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare) == 0x000008, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare) == 0x000080, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, Modules) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::Modules' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, SortedModules) == 0x000010, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::SortedModules' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, L_ArrayIndex) == 0x000020, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::L_ArrayIndex' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, L_Sorted) == 0x000024, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::L_Sorted' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, Temp_int_Variable) == 0x000028, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Add_IntInt_ReturnValue) == 0x00002C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Add_IntInt_ReturnValue_1) == 0x000030, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Add_IntInt_ReturnValue_2) == 0x000034, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Add_IntInt_ReturnValue_3) == 0x000038, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Array_Get_Item) == 0x000040, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Array_Get_Item_1) == 0x000048, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, K2Node_ClassDynamicCast_AsItem_Module_Skin) == 0x000050, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::K2Node_ClassDynamicCast_AsItem_Module_Skin' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, K2Node_ClassDynamicCast_bSuccess) == 0x000058, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, K2Node_ClassDynamicCast_AsItem_Module_Skin_1) == 0x000060, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::K2Node_ClassDynamicCast_AsItem_Module_Skin_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, K2Node_ClassDynamicCast_bSuccess_1) == 0x000068, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Conv_ByteToInt_ReturnValue) == 0x00006C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Conv_ByteToInt_ReturnValue_1) == 0x000070, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Conv_ByteToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Less_IntInt_ReturnValue) == 0x000074, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000075, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Array_Length_ReturnValue) == 0x000078, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_LessEqual_IntInt_ReturnValue) == 0x00007C, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare, CallFunc_Not_PreBool_ReturnValue) == 0x00007D, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_SortModulesByRare::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.Tick
// 0x003C (0x003C - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick) == 0x000004, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick) == 0x00003C, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick, MyGeometry) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick, InDeltaTime) == 0x000038, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_Tick::InDeltaTime' has a wrong offset!");

// Function UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List.UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C.ToggleInspectPivotOffset
// 0x0240 (0x0240 - 0x0000)
struct UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset final
{
public:
	bool                                          IsActive;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C81[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UInspectManagerComponent*               L_GunInspectManager;                               // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AItem_Gun_General*                      L_Gun;                                             // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class UTask_Menu_CameraSetFOV_C*              CallFunc_CreateAction_ReturnValue;                 // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInspectManagerComponent*               CallFunc_GetComponentByClass_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C82[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PG_PlayerState_Game_C*              K2Node_DynamicCast_AsBP_PG_Player_State_Game;      // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C83[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTask_Menu_CameraSetFOV_C*              CallFunc_CreateAction_ReturnValue_1;               // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DoesSocketExist_ReturnValue;              // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C84[0x7];                                     // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1; // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_1;          // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C85[0x8];                                     // 0x0088(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0090(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetSocketTransform_ReturnValue;           // 0x00F0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_Origin;                // 0x0150(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_BoxExtent;             // 0x0168(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetComponentBounds_SphereRadius;          // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C86[0x4];                                     // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0188(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x01A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x01B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_InverseTransformLocation_ReturnValue;     // 0x01D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_1;      // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0228(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset) == 0x000010, "Wrong alignment on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset");
static_assert(sizeof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset) == 0x000240, "Wrong size on UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, IsActive) == 0x000000, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::IsActive' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, L_GunInspectManager) == 0x000008, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::L_GunInspectManager' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, L_Gun) == 0x000010, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::L_Gun' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_CreateAction_ReturnValue) == 0x000018, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_CreateAction_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetComponentByClass_ReturnValue) == 0x000020, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetOwningPlayer_ReturnValue) == 0x000028, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, K2Node_DynamicCast_AsBP_PG_Player_State_Game) == 0x000038, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::K2Node_DynamicCast_AsBP_PG_Player_State_Game' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_CreateAction_ReturnValue_1) == 0x000048, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_CreateAction_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000050, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_Conv_StringToName_ReturnValue) == 0x000060, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_DoesSocketExist_ReturnValue) == 0x000068, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_DoesSocketExist_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1) == 0x000070, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_Conv_StringToName_ReturnValue_1) == 0x000080, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_Conv_StringToName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000090, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetSocketTransform_ReturnValue) == 0x0000F0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetSocketTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetComponentBounds_Origin) == 0x000150, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetComponentBounds_Origin' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetComponentBounds_BoxExtent) == 0x000168, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetComponentBounds_BoxExtent' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_GetComponentBounds_SphereRadius) == 0x000180, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_GetComponentBounds_SphereRadius' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakTransform_Location) == 0x000188, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakTransform_Rotation) == 0x0001A0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakTransform_Scale) == 0x0001B8, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_InverseTransformLocation_ReturnValue) == 0x0001D0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_InverseTransformLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakVector_X) == 0x0001E8, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakVector_Y) == 0x0001F0, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakVector_Z) == 0x0001F8, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakVector_X_1) == 0x000200, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakVector_Y_1) == 0x000208, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_BreakVector_Z_1) == 0x000210, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000218, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_Subtract_DoubleDouble_ReturnValue_1) == 0x000220, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_Subtract_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset, CallFunc_MakeVector2D_ReturnValue) == 0x000228, "Member 'UI_Game_SpawnScreen_Loadout_Full_Weapon_Gun_Gunsmith_Selector_List_C_ToggleInspectPivotOffset::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");

}

