#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_KillLog_Entry

#include "Basic.hpp"

#include "UI_KillLog_Entry_classes.hpp"
#include "UI_KillLog_Entry_parameters.hpp"


namespace SDK
{

// Function UI_KillLog_Entry.UI_KillLog_Entry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_KillLog_Entry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_KillLog_Entry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_KillLog_Entry.UI_KillLog_Entry_C.ExecuteUbergraph_UI_KillLog_Entry
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_KillLog_Entry_C::ExecuteUbergraph_UI_KillLog_Entry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_KillLog_Entry_C", "ExecuteUbergraph_UI_KillLog_Entry");

	Params::UI_KillLog_Entry_C_ExecuteUbergraph_UI_KillLog_Entry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_KillLog_Entry.UI_KillLog_Entry_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_KillLog_Entry_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_KillLog_Entry_C", "PreConstruct");

	Params::UI_KillLog_Entry_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

