#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress

#include "Basic.hpp"

#include "UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_classes.hpp"
#include "UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_parameters.hpp"


namespace SDK
{

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress.UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C.BndEvt__UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_Button_Back_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UUI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C::BndEvt__UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_Button_Back_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C", "BndEvt__UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_Button_Back_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress.UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C.ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C::ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C", "ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress");

	Params::UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress.UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C.OnUpdateGunData
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C::OnUpdateGunData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C", "OnUpdateGunData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress.UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C.OnUpdatePlayerCombinedInfo_Event
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<EModifiedData>                   ModifiedData                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FString                           CustomString                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C::OnUpdatePlayerCombinedInfo_Event(const TArray<EModifiedData>& ModifiedData, const class FString& CustomString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C", "OnUpdatePlayerCombinedInfo_Event");

	Params::UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C_OnUpdatePlayerCombinedInfo_Event Parms{};

	Parms.ModifiedData = std::move(ModifiedData);
	Parms.CustomString = std::move(CustomString);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress.UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C", "PreConstruct");

	Params::UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress.UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C.Reset
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress.UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C", "Tick");

	Params::UI_Menu_Solder_Weapon_Gun_Gunsmith_Progress_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

