#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector

#include "Basic.hpp"

#include "POLYGON_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector
// 0x0160 (0x0160 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_378C[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_378D[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APG_PlayerState_Menu*                   K2Node_DynamicCast_AsPG_Player_State_Menu;         // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_378E[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayFabJsonObject*                     CallFunc_GetPlayerCombinedInfo_ReturnValue;        // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPlayFabJsonObject*                     CallFunc_GetObjectField_ReturnValue;               // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPlayFabJsonObject*                     CallFunc_GetObjectField_ReturnValue_1;             // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPlayFabJsonObject*                     CallFunc_GetObjectField_ReturnValue_2;             // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetStringField_ReturnValue;               // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetStringField_ReturnValue_1;             // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FDateTime                              CallFunc_DateTimeFromIsoString_Result;             // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DateTimeFromIsoString_ReturnValue;        // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasField_ReturnValue;                     // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0072(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0073(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_378F[0x3];                                     // 0x0075(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0078(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_real_Variable;                                // 0x00B4(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_C*  CallFunc_FindParentWidgetOfType_ReturnValue;       // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPlayFabJsonObject*                     CallFunc_ConstructJsonObject_ReturnValue;          // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3790[0x7];                                     // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayFabJsonObject*                     K2Node_LowEntry_LocalVariable_Value__Object;       // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<float>                                 CallFunc_GetNumberArrayField_ReturnValue;          // 0x00D8(0x0010)(ReferenceParm)
	bool                                          CallFunc_DecodeJson_ReturnValue;                   // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x00E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3791[0x6];                                     // 0x00EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EModifiedData>                         K2Node_CustomEvent_ModifiedData;                   // 0x00F0(0x0010)(ConstParm, ReferenceParm)
	class FString                                 K2Node_CustomEvent_CustomString;                   // 0x0100(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void(TArray<EModifiedData>& ModifiedData, const class FString& CustomString)> K2Node_CreateDelegate_OutputDelegate;              // 0x0110(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_OldModulesInfo_C* CallFunc_Create_ReturnValue;                       // 0x0120(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDateTime                              CallFunc_MakeDateTime_ReturnValue;                 // 0x0128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              CallFunc_Subtract_DateTimeDateTime_ReturnValue;    // 0x0130(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTotalSeconds_ReturnValue;              // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0144(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3792[0x3];                                     // 0x0145(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector) == 0x000008, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector) == 0x000160, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, EntryPoint) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetOwningPlayer_ReturnValue) == 0x000008, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, Temp_bool_Has_Been_Initd_Variable) == 0x000010, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_DynamicCast_AsPG_Player_State_Menu) == 0x000018, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_DynamicCast_AsPG_Player_State_Menu' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetPlayerCombinedInfo_ReturnValue) == 0x000028, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetPlayerCombinedInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetObjectField_ReturnValue) == 0x000030, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetObjectField_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetObjectField_ReturnValue_1) == 0x000038, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetObjectField_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetObjectField_ReturnValue_2) == 0x000040, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetObjectField_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetStringField_ReturnValue) == 0x000048, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetStringField_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetStringField_ReturnValue_1) == 0x000058, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetStringField_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_DateTimeFromIsoString_Result) == 0x000068, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_DateTimeFromIsoString_Result' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_DateTimeFromIsoString_ReturnValue) == 0x000070, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_DateTimeFromIsoString_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_HasField_ReturnValue) == 0x000071, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_HasField_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, Temp_bool_Has_Been_Initd_Variable_1) == 0x000072, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_Event_IsDesignTime) == 0x000073, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, Temp_bool_IsClosed_Variable) == 0x000074, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_Event_MyGeometry) == 0x000078, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_Event_InDeltaTime) == 0x0000B0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, Temp_real_Variable) == 0x0000B4, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_FindParentWidgetOfType_ReturnValue) == 0x0000B8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_FindParentWidgetOfType_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_ConstructJsonObject_ReturnValue) == 0x0000C0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_ConstructJsonObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, Temp_bool_IsClosed_Variable_1) == 0x0000C8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_LowEntry_LocalVariable_Value__Object) == 0x0000D0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_LowEntry_LocalVariable_Value__Object' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetNumberArrayField_ReturnValue) == 0x0000D8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetNumberArrayField_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_DecodeJson_ReturnValue) == 0x0000E8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_DecodeJson_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_Array_Contains_ReturnValue) == 0x0000E9, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_CustomEvent_ModifiedData) == 0x0000F0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_CustomEvent_ModifiedData' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_CustomEvent_CustomString) == 0x000100, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_CustomEvent_CustomString' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, K2Node_CreateDelegate_OutputDelegate) == 0x000110, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_Create_ReturnValue) == 0x000120, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_MakeDateTime_ReturnValue) == 0x000128, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_MakeDateTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_Subtract_DateTimeDateTime_ReturnValue) == 0x000130, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_Subtract_DateTimeDateTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_PlayAnimation_ReturnValue) == 0x000138, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_GetTotalSeconds_ReturnValue) == 0x000140, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_GetTotalSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000144, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000148, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_PlayAnimationForward_ReturnValue) == 0x000150, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector, CallFunc_Greater_DoubleDouble_A_ImplicitCast) == 0x000158, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_ExecuteUbergraph_UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector::CallFunc_Greater_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.GetAllModuleSlots
// 0x0020 (0x0020 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots final
{
public:
	TArray<class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C*> Slots;                                             // 0x0000(0x0010)(Parm, OutParm, ContainsInstancedReference)
	TArray<class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C*> K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots) == 0x000008, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots) == 0x000020, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots, Slots) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots::Slots' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots, K2Node_MakeArray_Array) == 0x000010, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetAllModuleSlots::K2Node_MakeArray_Array' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.GetSlotByModuleType
// 0x0048 (0x0048 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType final
{
public:
	EGunModuleType                                ModuleType;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3793[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C* Param_Slot;                                        // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3794[0x4];                                     // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C*> CallFunc_GetAllModuleSlots_Slots;                  // 0x0020(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3795[0x4];                                     // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C* CallFunc_Array_Get_Item;                           // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType) == 0x000008, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType) == 0x000048, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, ModuleType) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::ModuleType' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, Param_Slot) == 0x000008, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::Param_Slot' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, Temp_int_Array_Index_Variable) == 0x000010, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, CallFunc_GetAllModuleSlots_Slots) == 0x000020, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::CallFunc_GetAllModuleSlots_Slots' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, CallFunc_Array_Get_Item) == 0x000038, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, CallFunc_Less_IntInt_ReturnValue) == 0x000040, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000041, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_GetSlotByModuleType::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.HideIncompatibleModuleSlots
// 0x0138 (0x0138 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots final
{
public:
	TSet<EGunModuleType>                          L_CompatibleModuleTypes;                           // 0x0000(0x0050)(Edit, BlueprintVisible)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3796[0x4];                                     // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C*> CallFunc_GetAllModuleSlots_Slots;                  // 0x0078(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C* CallFunc_Array_Get_Item;                           // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3797[0x3];                                     // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3798[0x7];                                     // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EGunModuleType>                        CallFunc_Set_ToArray_Result;                       // 0x00A0(0x0010)(ReferenceParm)
	EGunModuleType                                CallFunc_Array_Get_Item_1;                         // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3799[0x3];                                     // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C* CallFunc_GetSlotByModuleType_Slot;                 // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379A[0x7];                                     // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_ClassDynamicCast_AsItem_Gun_General;        // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379B[0x7];                                     // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGunModulesInfo*                        K2Node_DynamicCast_AsGun_Modules_Info;             // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379C[0x3];                                     // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGunModuleInfo                         CallFunc_Array_Get_Item_2;                         // 0x00F0(0x0040)(ContainsInstancedReference)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots) == 0x000008, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots) == 0x000138, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, L_CompatibleModuleTypes) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::L_CompatibleModuleTypes' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, Temp_int_Array_Index_Variable) == 0x000050, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, Temp_int_Loop_Counter_Variable) == 0x000054, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Add_IntInt_ReturnValue) == 0x000058, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, Temp_int_Loop_Counter_Variable_1) == 0x00005C, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, Temp_int_Array_Index_Variable_1) == 0x000060, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Add_IntInt_ReturnValue_1) == 0x000064, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, Temp_int_Loop_Counter_Variable_2) == 0x000068, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Add_IntInt_ReturnValue_2) == 0x00006C, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, Temp_int_Array_Index_Variable_2) == 0x000070, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_GetAllModuleSlots_Slots) == 0x000078, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_GetAllModuleSlots_Slots' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Array_Get_Item) == 0x000088, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_IsValid_ReturnValue) == 0x000090, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Array_Length_ReturnValue) == 0x000094, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Less_IntInt_ReturnValue) == 0x000098, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Set_ToArray_Result) == 0x0000A0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Set_ToArray_Result' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Array_Get_Item_1) == 0x0000B0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Array_Length_ReturnValue_1) == 0x0000B4, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_GetSlotByModuleType_Slot) == 0x0000B8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_GetSlotByModuleType_Slot' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000C0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, K2Node_ClassDynamicCast_AsItem_Gun_General) == 0x0000C8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::K2Node_ClassDynamicCast_AsItem_Gun_General' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, K2Node_ClassDynamicCast_bSuccess) == 0x0000D0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_LoadAsset_Blocking_ReturnValue) == 0x0000D8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_LoadAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, K2Node_DynamicCast_AsGun_Modules_Info) == 0x0000E0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::K2Node_DynamicCast_AsGun_Modules_Info' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, K2Node_DynamicCast_bSuccess) == 0x0000E8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Array_Length_ReturnValue_2) == 0x0000EC, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Array_Get_Item_2) == 0x0000F0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_Less_IntInt_ReturnValue_2) == 0x000130, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots, CallFunc_IsValidClass_ReturnValue) == 0x000131, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_HideIncompatibleModuleSlots::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.OnUpdateGunData
// 0x00F8 (0x00F8 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData final
{
public:
	class UPlayFabJsonObject*                     L_ContainerCustomData;                             // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379D[0x4];                                     // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_ClassDynamicCast_AsItem_Gun_General;        // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379E[0x7];                                     // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGunModulesInfo*                        K2Node_DynamicCast_AsGun_Modules_Info;             // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_379F[0x7];                                     // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayFabJsonObject*                     CallFunc_GetObjectField_ReturnValue;               // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPlayFabJsonObject*                     CallFunc_GetObjectField_ReturnValue_1;             // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37A0[0x4];                                     // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayFabJsonObject*                     CallFunc_GetObjectField_ReturnValue_2;             // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37A1[0x3];                                     // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         CallFunc_GetFieldNames_ReturnValue;                // 0x0070(0x0010)(ReferenceParm)
	struct FGunModuleInfo                         CallFunc_Array_Get_Item;                           // 0x0080(0x0040)(ContainsInstancedReference)
	class FString                                 CallFunc_Array_Get_Item_1;                         // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetStringField_ReturnValue;               // 0x00D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C* CallFunc_GetSlotByModuleType_Slot;                 // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37A2[0x3];                                     // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData) == 0x000008, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData) == 0x0000F8, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, L_ContainerCustomData) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::L_ContainerCustomData' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, Temp_int_Array_Index_Variable) == 0x000010, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, Temp_int_Loop_Counter_Variable_1) == 0x000014, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Add_IntInt_ReturnValue_1) == 0x000018, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, K2Node_ClassDynamicCast_AsItem_Gun_General) == 0x000020, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::K2Node_ClassDynamicCast_AsItem_Gun_General' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, K2Node_ClassDynamicCast_bSuccess) == 0x000028, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_LoadAsset_Blocking_ReturnValue) == 0x000030, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_LoadAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, K2Node_DynamicCast_AsGun_Modules_Info) == 0x000038, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::K2Node_DynamicCast_AsGun_Modules_Info' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_GetObjectField_ReturnValue) == 0x000048, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_GetObjectField_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_GetObjectField_ReturnValue_1) == 0x000050, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_GetObjectField_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Array_Length_ReturnValue) == 0x000058, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_GetObjectField_ReturnValue_2) == 0x000060, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_GetObjectField_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Less_IntInt_ReturnValue) == 0x000068, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, Temp_int_Array_Index_Variable_1) == 0x00006C, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_GetFieldNames_ReturnValue) == 0x000070, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_GetFieldNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Array_Get_Item) == 0x000080, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Array_Get_Item_1) == 0x0000C0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_GetStringField_ReturnValue) == 0x0000D0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_GetStringField_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_GetSlotByModuleType_Slot) == 0x0000E0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_GetSlotByModuleType_Slot' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x0000E8, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Array_Length_ReturnValue_1) == 0x0000EC, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000F0, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdateGunData::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.OnUpdatePlayerCombinedInfo_Event
// 0x0020 (0x0020 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event final
{
public:
	TArray<EModifiedData>                         ModifiedData;                                      // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FString                                 CustomString;                                      // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event) == 0x000008, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event) == 0x000020, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event, ModifiedData) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event::ModifiedData' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event, CustomString) == 0x000010, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_OnUpdatePlayerCombinedInfo_Event::CustomString' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_PreConstruct");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_PreConstruct) == 0x000001, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_PreConstruct");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.Reset
// 0x0038 (0x0038 - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37A3[0x4];                                     // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C*> CallFunc_GetAllModuleSlots_Slots;                  // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37A4[0x4];                                     // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_Slot_C* CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset) == 0x000008, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset) == 0x000038, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset, Temp_int_Array_Index_Variable) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset, CallFunc_GetAllModuleSlots_Slots) == 0x000010, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset::CallFunc_GetAllModuleSlots_Slots' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset, CallFunc_Array_Get_Item) == 0x000028, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset, CallFunc_Less_IntInt_ReturnValue) == 0x000030, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Reset::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector.UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C.Tick
// 0x003C (0x003C - 0x0000)
struct UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick) == 0x000004, "Wrong alignment on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick");
static_assert(sizeof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick) == 0x00003C, "Wrong size on UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick, MyGeometry) == 0x000000, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick, InDeltaTime) == 0x000038, "Member 'UI_Menu_Solder_Weapon_Gun_Gunsmith_Selector_C_Tick::InDeltaTime' has a wrong offset!");

}

