#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Shop_WeaponModules

#include "Basic.hpp"

#include "POLYGON_structs.hpp"


namespace SDK::Params
{

// Function UI_Shop_WeaponModules.UI_Shop_WeaponModules_C.AddNewModuleItem
// 0x00C8 (0x00C8 - 0x0000)
struct UI_Shop_WeaponModules_C_AddNewModuleItem final
{
public:
	class UClass*                                 ModuleId;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUI_ShopItem_C*                         CreatedItem;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          L_IsPremium;                                       // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3617[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 L_ModuleClass;                                     // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUI_ShopItem_C*                         L_CreatedItem;                                     // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWrapBox*                               Temp_object_Variable;                              // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWrapBox*                               Temp_object_Variable_1;                            // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWrapBox*                               Temp_object_Variable_2;                            // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWrapBox*                               Temp_object_Variable_3;                            // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWrapBox*                               Temp_object_Variable_4;                            // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWrapBox*                               Temp_object_Variable_5;                            // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EGunModuleType                                Temp_byte_Variable;                                // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x005A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x005B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x005C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3618[0x3];                                     // 0x005D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataContainerValue_Base*               CallFunc_FindDataContainerValue_ReturnValue;       // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UDataContainerValue_DataObject*         K2Node_DynamicCast_AsData_Object;                  // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3619[0x7];                                     // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataContainerValue_Base*               CallFunc_FindDataContainerValue_ReturnValue_1;     // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UDataContainerValue_Int32*              K2Node_DynamicCast_AsInt32;                        // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361A[0x7];                                     // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataContainerValue_Base*               CallFunc_FindDataContainerValue_ReturnValue_2;     // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UDataContainerValue_Int32*              K2Node_DynamicCast_AsInt32_1;                      // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361B[0x7];                                     // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWrapBox*                               K2Node_Select_Default;                             // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWrapBoxSlot*                           CallFunc_AddChildToWrapBox_ReturnValue;            // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUI_ShopItem_C*                         CallFunc_Create_ReturnValue;                       // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Shop_WeaponModules_C_AddNewModuleItem) == 0x000008, "Wrong alignment on UI_Shop_WeaponModules_C_AddNewModuleItem");
static_assert(sizeof(UI_Shop_WeaponModules_C_AddNewModuleItem) == 0x0000C8, "Wrong size on UI_Shop_WeaponModules_C_AddNewModuleItem");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, ModuleId) == 0x000000, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::ModuleId' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CreatedItem) == 0x000008, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CreatedItem' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, L_IsPremium) == 0x000010, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::L_IsPremium' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, L_ModuleClass) == 0x000018, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::L_ModuleClass' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, L_CreatedItem) == 0x000020, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::L_CreatedItem' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, Temp_object_Variable) == 0x000028, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, Temp_object_Variable_1) == 0x000030, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, Temp_object_Variable_2) == 0x000038, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, Temp_object_Variable_3) == 0x000040, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, Temp_object_Variable_4) == 0x000048, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::Temp_object_Variable_4' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, Temp_object_Variable_5) == 0x000050, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::Temp_object_Variable_5' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, Temp_byte_Variable) == 0x000058, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000059, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00005A, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_IsValid_ReturnValue) == 0x00005B, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_BooleanOR_ReturnValue) == 0x00005C, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_FindDataContainerValue_ReturnValue) == 0x000060, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_FindDataContainerValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, K2Node_DynamicCast_AsData_Object) == 0x000068, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::K2Node_DynamicCast_AsData_Object' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, K2Node_DynamicCast_bSuccess) == 0x000070, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_FindDataContainerValue_ReturnValue_1) == 0x000078, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_FindDataContainerValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, K2Node_DynamicCast_AsInt32) == 0x000080, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::K2Node_DynamicCast_AsInt32' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, K2Node_DynamicCast_bSuccess_1) == 0x000088, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_FindDataContainerValue_ReturnValue_2) == 0x000090, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_FindDataContainerValue_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, K2Node_DynamicCast_AsInt32_1) == 0x000098, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::K2Node_DynamicCast_AsInt32_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, K2Node_DynamicCast_bSuccess_2) == 0x0000A0, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, K2Node_Select_Default) == 0x0000A8, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_GetOwningPlayer_ReturnValue) == 0x0000B0, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_AddChildToWrapBox_ReturnValue) == 0x0000B8, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_AddChildToWrapBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_AddNewModuleItem, CallFunc_Create_ReturnValue) == 0x0000C0, "Member 'UI_Shop_WeaponModules_C_AddNewModuleItem::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function UI_Shop_WeaponModules.UI_Shop_WeaponModules_C.BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_Shop_WeaponModules_C_BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature final
{
public:
	class UUI_Button_C*                           Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Shop_WeaponModules_C_BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature) == 0x000008, "Wrong alignment on UI_Shop_WeaponModules_C_BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature");
static_assert(sizeof(UI_Shop_WeaponModules_C_BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature) == 0x000008, "Wrong size on UI_Shop_WeaponModules_C_BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature");
static_assert(offsetof(UI_Shop_WeaponModules_C_BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature, Button) == 0x000000, "Member 'UI_Shop_WeaponModules_C_BndEvt__UI_Button_Paint_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature::Button' has a wrong offset!");

// Function UI_Shop_WeaponModules.UI_Shop_WeaponModules_C.BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_Shop_WeaponModules_C_BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature final
{
public:
	class UUI_Button_C*                           Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Shop_WeaponModules_C_BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature) == 0x000008, "Wrong alignment on UI_Shop_WeaponModules_C_BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");
static_assert(sizeof(UI_Shop_WeaponModules_C_BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature) == 0x000008, "Wrong size on UI_Shop_WeaponModules_C_BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");
static_assert(offsetof(UI_Shop_WeaponModules_C_BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature, Button) == 0x000000, "Member 'UI_Shop_WeaponModules_C_BndEvt__UI_Shop_WeaponModules_UI_Button_Strap_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature::Button' has a wrong offset!");

// Function UI_Shop_WeaponModules.UI_Shop_WeaponModules_C.ExecuteUbergraph_UI_Shop_WeaponModules
// 0x0100 (0x0100 - 0x0000)
struct UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361C[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable;                              // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGunModulesInfo*                        K2Node_DynamicCast_AsGun_Modules_Info;             // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361D[0x3];                                     // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361E[0x3];                                     // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361F[0x4];                                     // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGunModuleInfo                         CallFunc_Array_Get_Item;                           // 0x0050(0x0040)(ContainsInstancedReference)
	class UUI_ShopItem_C*                         CallFunc_AddNewModuleItem_CreatedItem;             // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3620[0x7];                                     // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           CallFunc_GetDataTableRowNames_OutRowNames;         // 0x00A0(0x0010)(ReferenceParm)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item_1;                         // 0x00B4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3621[0x4];                                     // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FItemEntry                             CallFunc_GetDataTableRowFromName_OutRow;           // 0x00C0(0x0010)()
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3622[0x3];                                     // 0x00D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsItem_Gun_General;        // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3623[0x3];                                     // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3624[0x7];                                     // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Button_C*                           K2Node_ComponentBoundEvent_Button_1;               // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUI_Button_C*                           K2Node_ComponentBoundEvent_Button;                 // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules) == 0x000008, "Wrong alignment on UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules");
static_assert(sizeof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules) == 0x000100, "Wrong size on UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, EntryPoint) == 0x000000, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_CustomEvent_Loaded) == 0x000008, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, Temp_object_Variable) == 0x000020, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_DynamicCast_AsGun_Modules_Info) == 0x000028, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_DynamicCast_AsGun_Modules_Info' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, Temp_int_Array_Index_Variable) == 0x000034, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, Temp_int_Loop_Counter_Variable) == 0x00003C, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Less_IntInt_ReturnValue) == 0x000040, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Add_IntInt_ReturnValue) == 0x000044, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, Temp_int_Array_Index_Variable_1) == 0x000048, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Array_Get_Item) == 0x000050, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_AddNewModuleItem_CreatedItem) == 0x000090, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_AddNewModuleItem_CreatedItem' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_Event_IsDesignTime) == 0x000098, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_GetDataTableRowNames_OutRowNames) == 0x0000A0, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_GetDataTableRowNames_OutRowNames' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, Temp_int_Loop_Counter_Variable_1) == 0x0000B0, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Array_Get_Item_1) == 0x0000B4, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_GetDataTableRowFromName_OutRow) == 0x0000C0, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x0000D0, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000D4, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_ClassDynamicCast_AsItem_Gun_General) == 0x0000D8, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_ClassDynamicCast_AsItem_Gun_General' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_ClassDynamicCast_bSuccess) == 0x0000E0, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Array_Length_ReturnValue_1) == 0x0000E4, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000E8, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_ComponentBoundEvent_Button_1) == 0x0000F0, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules, K2Node_ComponentBoundEvent_Button) == 0x0000F8, "Member 'UI_Shop_WeaponModules_C_ExecuteUbergraph_UI_Shop_WeaponModules::K2Node_ComponentBoundEvent_Button' has a wrong offset!");

// Function UI_Shop_WeaponModules.UI_Shop_WeaponModules_C.OnLoaded_661D94784290BA359719499C39B3D723
// 0x0008 (0x0008 - 0x0000)
struct UI_Shop_WeaponModules_C_OnLoaded_661D94784290BA359719499C39B3D723 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Shop_WeaponModules_C_OnLoaded_661D94784290BA359719499C39B3D723) == 0x000008, "Wrong alignment on UI_Shop_WeaponModules_C_OnLoaded_661D94784290BA359719499C39B3D723");
static_assert(sizeof(UI_Shop_WeaponModules_C_OnLoaded_661D94784290BA359719499C39B3D723) == 0x000008, "Wrong size on UI_Shop_WeaponModules_C_OnLoaded_661D94784290BA359719499C39B3D723");
static_assert(offsetof(UI_Shop_WeaponModules_C_OnLoaded_661D94784290BA359719499C39B3D723, Loaded) == 0x000000, "Member 'UI_Shop_WeaponModules_C_OnLoaded_661D94784290BA359719499C39B3D723::Loaded' has a wrong offset!");

// Function UI_Shop_WeaponModules.UI_Shop_WeaponModules_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Shop_WeaponModules_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Shop_WeaponModules_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Shop_WeaponModules_C_PreConstruct");
static_assert(sizeof(UI_Shop_WeaponModules_C_PreConstruct) == 0x000001, "Wrong size on UI_Shop_WeaponModules_C_PreConstruct");
static_assert(offsetof(UI_Shop_WeaponModules_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Shop_WeaponModules_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_Shop_WeaponModules.UI_Shop_WeaponModules_C.SetActivePage
// 0x0050 (0x0050 - 0x0000)
struct UI_Shop_WeaponModules_C_SetActivePage final
{
public:
	int32                                         Param_Index;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3625[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Button_C*                           Button;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3626[0x4];                                     // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0020(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3627[0x4];                                     // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Button_C*                           K2Node_DynamicCast_AsUI_Button;                    // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Shop_WeaponModules_C_SetActivePage) == 0x000008, "Wrong alignment on UI_Shop_WeaponModules_C_SetActivePage");
static_assert(sizeof(UI_Shop_WeaponModules_C_SetActivePage) == 0x000050, "Wrong size on UI_Shop_WeaponModules_C_SetActivePage");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, Param_Index) == 0x000000, "Member 'UI_Shop_WeaponModules_C_SetActivePage::Param_Index' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, Button) == 0x000008, "Member 'UI_Shop_WeaponModules_C_SetActivePage::Button' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, Temp_int_Array_Index_Variable) == 0x000010, "Member 'UI_Shop_WeaponModules_C_SetActivePage::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'UI_Shop_WeaponModules_C_SetActivePage::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'UI_Shop_WeaponModules_C_SetActivePage::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, CallFunc_GetAllChildren_ReturnValue) == 0x000020, "Member 'UI_Shop_WeaponModules_C_SetActivePage::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, CallFunc_Array_Get_Item) == 0x000030, "Member 'UI_Shop_WeaponModules_C_SetActivePage::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'UI_Shop_WeaponModules_C_SetActivePage::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, K2Node_DynamicCast_AsUI_Button) == 0x000040, "Member 'UI_Shop_WeaponModules_C_SetActivePage::K2Node_DynamicCast_AsUI_Button' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'UI_Shop_WeaponModules_C_SetActivePage::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Shop_WeaponModules_C_SetActivePage, CallFunc_Less_IntInt_ReturnValue) == 0x000049, "Member 'UI_Shop_WeaponModules_C_SetActivePage::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

}

